### PR TITLE
Remove unwanted launcher icons to avoid gradle build conflicts

### PR DESCRIPTION
**Pull request by vishyrich**
Upgrade to android plugin version 1.3.x results in build errors if duplicate launcher icons are present in library projects. Hence deleting ic_launcher icons to avoid build conflicts

https://code.google.com/p/android/issues/detail?id=171089
http://stackoverflow.com/questions/29965398/gradle-finished-with-non-zero-exit-value-1-ic-launcher-png-error-duplicate-fi

### CODE REVIEW

**Comment by KeithYokoma** [comment]
[LGTM](http://lgtm.in/i/WlY74F5bq)

[:+1:](http://lgtm.in/u/WlY74F5bq)

**Comment by vishyrich** [comment]
早い！！
thnx!!!

**Comment by vishyrich** [comment]
@KeithYokoma さん

早い！！thanks for the review
マージもお願いします〜

**Comment by KeithYokoma** [comment]
僕マージの権限持ってないみたいなので、どなたかお願いします！

**Pull request merged**
